### ISSUE TITLE
Readme Instructions not clear or complete. 

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaDebug/Debugger.jl#110]
Hello all, I am trying to use this package to help on one of my projects.  I do the following: 

`using Debugger

function foo(n)
    x = n+1
    ((BigInt[1 1; 1 0])^x)[2,1]
end

@enter foo(20)
`

I get the following: 

`WARNING: both Debugger and Juno export "@enter"; uses of it in module Main must be qualified
ERROR: LoadError: LoadError: UndefVarError: @enter not defined`

What can I do to resolve this?

**Comment by pfitzseb** [comment]
You can just use `Debugger.@enter foo(20)`, as the warning suggests. The Debugger-integration for Juno is imminent though.

The fact that Juno exports its own `@enter` and `breakpoint` might not be great though -- opinions, @KristofferC, @timholy?

**Comment by logankilpatrick** [comment]
Awesome, that worked.  Maybe have the warning say to do exactly what you just said because it was not clear to me.  I can make that change and submit a pull request if you want @pfitzseb

**Comment by KristofferC** [comment]
Yeah, that's not optimal. So Juno has its own way to enter debug mode from the REPL? Call it something else? :p.

**Comment by logankilpatrick** [comment]
Why when I get it to run, and I press "s" in the Debugger, does it say "Unknown command ``. Executing `?` to obtain help.".  Do I need to use some special syntax when entering basic commands or just "s" or another single character?   @KristofferC  @pfitzseb

**Comment by pfitzseb** [comment]
> Yeah, that's not optimal. So Juno has its own way to enter debug mode from the REPL? Call it something else? :p.

Hmm, I could just not export it... But yes, of course Juno has it's own way -- you guys didn't want me to depend on Debugger.jl :D

>  Do I need to use some special syntax when entering basic commands or just "s" or another single character?

You shouldn't. Maybe something went wrong when installing.

**Comment by logankilpatrick** [comment]
@pfitzseb  This may be an issue related to Juno integration.  I uninstalled and reinstalled, and out of the box, it does not work.  If I mess around with it a little, (by pressing enter a few times and then backspace a few times, I can get it to work). Not sure what the root cause of this is, but I am happy to provide more details if that is relevant. (Currently working on a Macbook pro with Atom and Juno integration in Julia 1.0.3).

**Comment by timholy** [comment]
If you want to be fancy, you could `import Debugger` and then `using Debugger: break_on, ...` but omit `@enter` from the list. Define your own `@enter` which then calls `getfield(Debugger, Symbol("#@foo"))`. Export your `@enter` along with all the unchanged methods of Debugger.

But then, if the user says `using Debugger` in the Juno console, it will break. So it's not a bad idea to use a new name.

**Comment by KristofferC** [comment]
https://github.com/JuliaDebug/Debugger.jl/pull/111#issuecomment-475212211
