### ISSUE TITLE
CTRL-C should pause the debugger

### ISSUE THREAD

**Issue by staticfloat** [JuliaDebug/Debugger.jl#121]
When the debugger is running, it would be good for CTRL-C to interrupt the debugger and allow for resumption/inspection wherever it happened to fall.  Currently, it breaks something:

```
julia> using Pkg, Debugger
       @enter Pkg.add("JpegTurbo_jll")
In #add#20(kwargs, , pkg) at /Users/sabae/src/Pkg.jl/src/API.jl
>64  add(pkg::Union{AbstractString, D}; kwargs...) where {D <: Dependency} = add([pkg]; kwargs...)

About to run: (Base.vect)("JpegTurbo_jll")
1|debug> n
^CERROR: MethodError: no method matching iterate(::InterruptException)
Closest candidates are:
  iterate(::Core.SimpleVector) at essentials.jl:568
  iterate(::Core.SimpleVector, ::Any) at essentials.jl:568
  iterate(::ExponentialBackOff) at error.jl:199
  ...
```

**Comment by KristofferC** [comment]
Hm, seems to work for me:

```
julia> f(x) = for i in 1:100 sleep(0.05) end

julia> break_on(:error)

julia> @enter f(5)
In f(x) at REPL[1]
>1  f(x) = for i in 1:100 sleep(0.05) end

About to run: (Colon())(1, 100)
1|debug> n
Breaking for error:
ERROR: InterruptException:
In stream_wait(x, c) at stream.jl
 45  preserve_handle(x)
 46  try
 47      return wait(c...)
 48  finally
>49      unpreserve_handle(x)
 50  end

About to run: (rethrow)()
1|debug> 
```

Can you put a `rethrow(err)` at https://github.com/JuliaDebug/Debugger.jl/blob/master/src/repl.jl#L40 so we can see the stacktrace where the `iterate` failed.

**Comment by KristofferC** [comment]
Also, fwiw, Pkg is quite notorious for being hard on the interpreter.

**Comment by staticfloat** [comment]
> Also, fwiw, Pkg is quite notorious for being hard on the interpreter.

Heh, yes.  But the debugger so far is quite the fun tool to use, so stress-test it I must.

> Can you put a rethrow(err) at /src/repl.jl@master#L40 so we can see the stacktrace where the iterate failed.

Intriguingly, it doesn't show it, and I now get some weird hybrid behavior where I still get the error, but debugging seems to be able to continue:

```
julia> using Pkg, Debugger
       break_on(:error)
       @run Pkg.add("JpegTurbo_jll")
^CBreaking for error:
ERROR: MethodError: no method matching iterate(::InterruptException)
Closest candidates are:
  iterate(::Core.SimpleVector) at essentials.jl:568
  iterate(::Core.SimpleVector, ::Any) at essentials.jl:568
  iterate(::ExponentialBackOff) at error.jl:199
  ...
In #open#310(kwargs, , f, args) at iostream.jl
 367  io = open(args...; kwargs...)
 368  try
 369      f(io)
 370  finally
>371      close(io)
 372  end

About to run: (rethrow)()
1|debug>
```

**Comment by staticfloat** [comment]
Even though it says `About to run: (rethrow)()`, asking for a backtrace gives the backtrace of where in `Pkg` I was sitting when I hit CTRL-C.

**Comment by KristofferC** [comment]
I've tried to trackdown where the 

```
ERROR: MethodError: no method matching iterate(::InterruptException)
Closest candidates are:
  iterate(::Core.SimpleVector) at essentials.jl:568
  iterate(::Core.SimpleVector, ::Any) at essentials.jl:568
  iterate(::ExponentialBackOff) at error.jl:199
```

comes from, but so far, has not been successful.

**Comment by KristofferC** [comment]
Ok, I think it might be here:

https://github.com/JuliaLang/Pkg.jl/blob/101519a3e7829bcb14938434e50a9f8d4fdb6b80/src/project.jl#L134-L135

**Comment by KristofferC** [comment]
To summarize:

The weird `iterate` error is correct and due to a bug in Pkg: https://github.com/JuliaLang/Pkg.jl/issues/1120.

The backtrace is also correct since we are throwing from the `try` in the `open(...) do` syntax.

So what is left to do here is #145 to get a good backtrace for the error when we break on error.
