### ISSUE TITLE
Support for jupyter lab / IJulia?

### ISSUE THREAD

**Issue by nickeubank** [JuliaDebug/Debugger.jl#125]
I tried using this in an IJulia console but ran into issues:

```
using Debugger; break_on(:error)
function test()
    x = a_non_existant_variable + 1
end
@run test()
```

Gets me:

```
UndefVarError: active_repl not defined

Stacktrace:
 [1] (::getfield(Debugger, Symbol("#kw##RunDebugger")))(::NamedTuple{(:initial_continue,),Tuple{Bool}}, ::typeof(Debugger.RunDebugger), ::JuliaInterpreter.Frame) at ./none:0
 [2] top-level scope at /Users/Nick/.julia/packages/Debugger/xhyyB/src/Debugger.jl:109
 [3] top-level scope at In[7]:1
```

**Comment by fredrikekre** [comment]
IJulia is not a REPL so not sure how a REPL based Debugger can work there.

**Comment by KristofferC** [comment]
We can give a better error message though.

**Comment by nickeubank** [comment]
@fredrikekre Why isn't it a REPL? Jupyter Notebooks aren't a REPL, but jupyter labs offers a console interface that's as REPL as anything I can think of...

![image](https://user-images.githubusercontent.com/9683693/54754434-868a0e80-4bb1-11e9-9e13-4408b850c862.png)

**Comment by KristofferC** [comment]
That is a REPL, but it is not the standard Julia REPL which this package builds its interface on top of.

**Comment by nickeubank** [comment]
OK, that's totally reasonable. Just confused by @fredrikekre 's comment. Thanks!

**Comment by timholy** [comment]
You can use JuliaInterpreter directly:

```julia
using JuliaInterpreter
@breakpoint foo(x, y)
frame, pc = @interpret foo(x, y)
debug_command(frame, :s)
...
```
