### ISSUE TITLE
Command to display more lines of context than st?

### ISSUE THREAD

**Issue by fsaad** [JuliaDebug/Debugger.jl#135]
When using `st` the debugger shows the current line (645) that is about to be executed:

```
$ julia
julia> @enter sum(A)
In #sum#540(dims, , a) at reducedim.jl:645
>645  @inline ($fname)(a::AbstractArray; dims=:) = ($_fname)(a, dims)

About to run: (Base._sum)([9, 10, 3, 1, 5], Colon())
1|debug> 
```

Is there a command to show more lines e.g., lines 640--650?

In, for example `ipdb`, the command to get more lines of context is `ll`, as illustrated below:

```
$ ipython
In [1]: import ipdb
In [2]: def f():
   ...:        x = 2
   ...:        y = 10
   ...:        import ipdb; ipdb.set_trace()
   ...:        z = 100
   ...:        return 1
   ...: 
In [3]: f()
> <ipython-input-2-05f0cfef2a35>(5)f()
      4        import ipdb; ipdb.set_trace()
----> 5        z = 100
      6        return 1
ipdb> ll
      1 def f():
      2        x = 2
      3        y = 10
      4        import ipdb; ipdb.set_trace()
----> 5        z = 100
      6        return 1
ipdb>
```

**Comment by KristofferC** [comment]
The reason it is not showing you more lines is that the whole function is a one liner. In the examples you gave you didnät show anything outside the function either. If the function has more lines, more lines are shown:

```
julia> function f()
           x = 2
           y = sin(10)
           @bp
           z = 100
           return 1
       end
f (generic function with 1 method)

julia> @run f()
Hit breakpoint:
In f() at REPL[10]:2
 2      x = 2
 3      y = sin(10)
●4      @bp
 5      z = 100
>6      return 1
 7  end

About to run: return 1
1|debug> 
```

**Comment by fsaad** [comment]
Thanks for the quick response. Is there still a way to view more lines of context than the default number shown by the debugger? Or is there a way to configure the default number of context lines?

**Comment by KristofferC** [comment]
You can change this variable whenever: https://github.com/JuliaDebug/Debugger.jl/blob/a90df952c3cd048209b4d7997277deb13441b2d7/src/printing.jl#L128

We should make it configurable, it just hasn't been a priority so far.
