### ISSUE TITLE
Omit error message (i.e. assume ?) for empty command

### ISSUE THREAD

**Issue by waldyrious** [JuliaDebug/Debugger.jl#146]
Currently simply pressing Enter in the debug prompt shows an error message:

```
1|debug>
Unknown command ``. Executing `?` to obtain help.
  Basic Commands:
  - st: show the status
 ...
```

I find the error message would make more sense if an actual command had been inserted. Perhaps emulating the behavior of `git add --patch` (i.e. immediately printing the help message for an empty command) would provide a better experience:

```
1|debug>
  Basic Commands:
  - st: show the status
 ...
```

Or, if we want to be more explicit:

```
1|debug>
Executing `?` to obtain help.
  Basic Commands:
  - st: show the status
 ...
```

**Comment by KristofferC** [comment]
An empty command repeats the last command so this is only relevant if one enters an empty command as the very first command. Could be fixed but quite low priority.

**Comment by waldyrious** [comment]
> An empty command repeats the last command

I noticed that too, it confused me at first. It is perhaps a separate issue, but I'd find it more intuitive if the prompt indicated what default action it would take, e.g.

```
1|debug> [?]
```

Or again, use something like `git add --patch`:

```
Stage this hunk [y,n,q,a,d,e,?]?
```

**Comment by KristofferC** [comment]
Showing the prompt as `1|debug [n]>` where `[n]` is the command that would be executed on enter (and perhaps starting it as `1|debug [?]>`m and not showing the `Unknown command` on the first enter would probably work well.

**Comment by pfitzseb** [comment]
Hm or we could just restore the previous input?

**Comment by KristofferC** [comment]
You mean showing it as `1|debug> nc` for example where `nc` has been pre-entered?

**Comment by pfitzseb** [comment]
Yes.

**Comment by fredrikekre** [comment]
Would be annoying if you have to backspace everytime you want to change command though.

**Comment by pfitzseb** [comment]
Could only print it, so as soon as you enter something else the previous input vanishes.

**Comment by KristofferC** [comment]
> Could only print it, so as soon as you enter something else the previous input vanishes.

That seems pretty magical. Often when there are default values they are showed in the prompt, something like `[Y]/N` and then you enter what you want while not entering anything executes the default.

**Comment by KristofferC** [comment]
So thinking a bit more about this this, I don't like the prompt changing all the time so I think we should just fix the ```Unknown command `` ``` and that's it and put a comment in the README about repeating the earlier command.

**Comment by waldyrious** [comment]
> I don't like the prompt changing all the time

In terms of the UX or the implementation? If you're concerned about the UX, I think the prompt being explicit about what will happen is more valuable than avoiding a 1- or 2-char command inside `[]` changing. Especially since the behavior of the tool when Enter is pressed indeed does change all the time (if it repeats the last command), so it's only fair that the prompt reflects this.

As additional data, `git add --patch` does change the list of options it shows to the user (e.g. the `s` option is not listed if the current hunk cannot be split further), and that never bothered me (I only noticed that when I wanted to demonstrate the various commands to a friend and the `s` wasn't there).

Alternatively, we could simply have `?` be the default command all the time, rather than repeat the last command — in which case I agree that we could omit the `[]`.
