### ISSUE TITLE
Logo/icon ideas

### ISSUE THREAD

**Issue by cormullion** [JuliaDebug/Debugger.jl#167]
Here's 5 ideas for logos/icons for JuliaDebug(ger)... Comments/criticisms/votes welcome... :)

<img width="800" alt="Screenshot 2019-04-04 at 18-800 31-800 16-800" src="https://user-images.githubusercontent.com/52289/55576037-34e09880-5708-11e9-9ee0-92b87cf66846.png">

**Comment by timholy** [comment]
I especially like the magnifying glass one, but they're all great!

**Comment by KristofferC** [comment]
Agree with Tim that they are all awesome. The magnifying glass is my favorite as well!

**Comment by pfitzseb** [comment]
Great work! Ditto re the last logo, I think.

**Comment by sbromberger** [comment]
Reminds me of 

![](https://i.redd.it/7yxyxxgrswrx.jpg)

which disturbs me a bit.

**Comment by mkborregaard** [comment]
I love number 2

**Comment by KristofferC** [comment]
@cormullion, do you have a high res one for the magnifying glass one? Perhaps the "glass shade" on it can be removed though? Makes it a bit "cleaner".

**Comment by StefanKarpinski** [comment]
I love these! My order of preference: 2, 5, 1.

**Comment by sbromberger** [comment]
Number 4 is really clever.

**Comment by cormullion** [comment]
@KristofferC Sure. 

![debug](https://user-images.githubusercontent.com/52289/55612446-2e8e0300-5780-11e9-8734-a198a53951db.png)

(Code is [here](https://gist.github.com/cormullion/7f5d5708cfc81add014f2ecb2ef263f8).)

Thanks guys!

**Comment by KristofferC** [comment]
Logo is updated!

**Comment by StefanKarpinski** [comment]
Very small nit: the background of the logo is white, not transparent, and the background in GitHub is slightly off-white so you can see the background square. Would it be possible to generate an image with a transparent background instead of white?

**Comment by KristofferC** [comment]
I noticed that as well, fought with Windows Paint for 15 minutes and decided to ignore it.

**Comment by KristofferC** [comment]
Ok, should be fixed now.

**Comment by StefanKarpinski** [comment]
Nice! Looks great. Did you just delete the lines where it paints the background white? I was going to try that but you beat me to it.

**Comment by KristofferC** [comment]
https://www110.lunapic.com/editor/?action=transparent >P

**Comment by cormullion** [comment]
Blimey, you're right, it's `(0.98, 0.98, 0.99)`... Perhaps I should turn the brightness on my monitor up... :) I updated the Gist code for posterity.
