### ISSUE TITLE
does not enter Pkg.test -> workaround?

### ISSUE THREAD

**Issue by lobingera** [JuliaDebug/Debugger.jl#168]
Maybe it's only me, but i'd like (need) to debug something in the test of a package, so
`@enter` Pkg.test("Cairo") 
looked natural, but the next 'n' freezes - as Pkg.test enters a subprocess.

**Comment by KristofferC** [comment]
Debugger.jl only handles debugging function calls at the moment. So you would have to `include` the `runtests.jl` file and then call the function you want to debug.
