### ISSUE TITLE
Add `up`/`down` commands to navigate the stack frame

### ISSUE THREAD

**Issue by Keno** [JuliaDebug/Debugger.jl#176]
I thought we had these already, but it doesn't appear that way. Like in gdb/lldb, I'd appreciate `up`/`down` commands to go to the next higher or lower stack frame respectively. I.e. if I'm in stack frame `11`, up would put me into stack frame `12` and down would put me into stack frame `10`.

**Comment by KristofferC** [comment]
Up and down are already used for navigating the history. We could remove that.

**Comment by pfitzseb** [comment]
I think Keno meant the literal [`up` and `down` commands](http://visualgdb.com/gdbreference/commands/up).

**Comment by KristofferC** [comment]
Oh. Haha, alright.
