### ISSUE TITLE
StatsModels not accessible 

### ISSUE THREAD

**Issue by xtk923** [JuliaDebug/Debugger.jl#180]
When trying to add GLM, julia repl returns 404 for StatsModels.

**Comment by KristofferC** [comment]
Not sure how this is a Debugger.jl problem but see https://discourse.julialang.org/t/juliastats-statsmodels-package-missing/23880

**Comment by xtk923** [comment]
Thanks for your response! I opened issue pages for both repo, and posted the issue here by mistake. That's why I closed the issue immediately.
