### ISSUE TITLE
Where is the setting of breakpoints?

### ISSUE THREAD

**Issue by PetrKryslUCSD** [JuliaDebug/Debugger.jl#184]
When I enter some code the debug prompt shows up. I type in "?", and this is what gets printed:
![image](https://user-images.githubusercontent.com/9855832/58064653-dba5ba80-7b37-11e9-8e8c-cccbd28afcb0.png)
No mention of any breakpoint-setting commands. The readme talks about `bp`: That is nowhere in sight. What is going on? Am I using it right?

**Comment by fredrikekre** [comment]
The README is applicable to the master branch. `pkg> add Debugger#master` should get you the interface described in the README, see also https://github.com/JuliaDebug/Debugger.jl/pull/183.

**Comment by PetrKryslUCSD** [comment]
Got it!

**Comment by KristofferC** [comment]
You also need `JuliaInterpreter#master`.

**Comment by PetrKryslUCSD** [comment]
Great, that worked. I do have some questions concerning the display of the breakpoints:

![image](https://user-images.githubusercontent.com/9855832/58111910-3b877a00-7ba7-11e9-8c95-65ca7975043b.png)
I think line 7 and later lines 7 and 9 (after I added another breakpoint) should be shown with a red dot. However 8 is also decorated with a red dot as you can see above. Is that a bug?

**Comment by KristofferC** [comment]
Maybe, I'll try it out.

**Comment by KristofferC** [comment]
When you ran `bp add 9` it shows a breakpoint on line 8 and 9. So I think you already had a breakpoint on line 8 (perhaps from a previous session). Breakpoints are not cleared between sessions.

**Comment by PetrKryslUCSD** [comment]
That is possible. I have tried to reproduce, but this time after restart. The multiple breakpoints did not appear.

**Comment by KristofferC** [comment]
https://github.com/JuliaDebug/Debugger.jl/commit/372379293c9ff3c6212813ad97bd1dc8d59a27c3#commitcomment-33697847
