### ISSUE TITLE
Debugger is slow

### ISSUE THREAD

**Issue by timholy** [JuliaDebug/Debugger.jl#19]
Using [this example](https://github.com/JuliaDebug/JuliaInterpreter.jl/blob/2f5a96f3ca851561bb06354cf2249ee45239ee0c/test/interpret.jl#L7-L13) and `A = rand(10^3)`:

```julia
julia> frame = JuliaInterpreter.enter_call(summer, A);

julia> stack = JuliaStackFrame[];

julia> @time JuliaInterpreter.finish_and_return!(stack, frame)
  0.045237 seconds (193.26 k allocations: 4.834 MiB)
503.8382182562312

julia> frame = JuliaInterpreter.enter_call(summer, A);

julia> @time step_through(frame)
  0.409519 seconds (1.33 M allocations: 76.884 MiB, 1.94% gc time)
503.8382182562312
```
This is going to be a problem if we use Debugger for runtime execution with breakpoints.

I haven't diagnosed the bottlenecks yet, and that's obviously the first step. But one option is to rewrite the control-flow aspects of Debugger in "raw JuliaInterpreter" and then make this package "just a REPL mode." Thoughts?

**Comment by KristofferC** [comment]
Yes, having this package as "just a REPL mode" was something I recently thought about as well. It also seems like the correct structuring to simplify writing other frontends to the debugger (e.g. for IDEs).

**Comment by KristofferC** [comment]
Although I am not sure the time for `step_through` is such an important thing to measure? It just simulates someone repeatedly pressing the `s` button to step through the whole code (AFAIU as just a way to test the debugger). I think any debugger would be slow if run in such a manner?

**Comment by timholy** [comment]
If we implement "continue until you hit the next breakpoint or error" in raw JuliaInterpreter, then when we pass control back to Debugger we are going to have to construct a stack that looks as if we had just been stepping through in Debugger. Perhaps that will be trivial, but I haven't looked into it.

**Comment by KristofferC** [comment]
Yes we would need to reconstruct the stack (vector of `JuliaStackFrame`) but perhaps that is not too bad? Also, how about instead of having the stack as a Vector, we have it as a linked list where each frame has a pointer to its parent. Then there is no need to keep a stack at all, one could just walk upwards from any given frame.

**Comment by timholy** [comment]
Ah, I had remembered that each item on the stack was a separate type, rather than having a `Vector{JuliaStackFrame}`. Right, this doesn't sound like a big problem.

WRT linked-list, interesting, but what's the main goal? To get rid of that `stack` argument for many JuliaInterpreter functions? It's useful if you want to pass `Compiled()` instead to control recursion.

Speaking of performance, I've also been thinking that some day we might want to add `CompiledLogger()`, which would implement a Rebugger-like "record all input arguments upon entry" mode and otherwise run as compiled code. That might help mitigate JuliaInterpreter's performance problems. If you're debugging and break-on-error, you wouldn't be able to start at the exact line that threw the error but at least you'd be able to restart at the top of the function that threw the error. Then from that point you could run in true interpreted mode.

I'll close this since you've convinced me that this isn't a major problem, but of course we can keep discussing issues in this thread.

**Comment by KristofferC** [comment]
> WRT linked-list, interesting, but what's the main goal? To get rid of that `stack` argument for many JuliaInterpreter functions? I

Yes, that would be one advantage.

> If you're debugging and break-on-error, you wouldn't be able to start at the exact line that threw the error but at least you'd be able to restart at the top of the function that threw the error.

Evaluating code twice implies rewinding which for functions with any mutation is not possible, no?

**Comment by timholy** [comment]
> Evaluating code twice implies rewinding which for functions with any mutation is not possible, no?

Unless you `deepcopy` on entry. This is what Rebugger does. So far it hasn't been a major source of trouble, but until this morning :smile: Rebugger had so many functions it couldn't find, I'm not sure that's meaningful.

Another potential approach to improving the performance would be to create a `FrameCompiler.jl` package that basically does the steps taken by JuliaInterpreter, but runs on typeinferred code and does only "the thing that matters." For each frame, it would create a function that takes `locals` and `ssavalues` as the two inputs, and then updates them as it executes the method body. I'm not sure how much of a gain that would result in, but hopefully at least 10x. But that's clearly stage 2, once the dust has settled on JuliaInterpreter.
