### ISSUE TITLE
Automatically wrap expression passed to @enter in a function?

### ISSUE THREAD

**Issue by tkf** [JuliaDebug/Debugger.jl#222]
Currently, `@enter` fails with complex expressions like broadcasting and do notation.  I usually just wrap them in a function and call `@enter`.  Is it reasonable to do this automatically?

**Comment by KristofferC** [comment]
Maybe? Feels like a thing that needs to be tried out and then we'll see.

**Comment by timholy** [comment]
Some things have to be run at top level. While this is vital for JuliaInterpreter/Revise, ATM I'm struggling to come up with an example that might be of interest to `@enter`---it might indeed be safe in this case. I agree with @KristofferC, I'd want someone running with such a patch for a while (couple of weeks at least) so we can detect any problems it causes.
