### ISSUE TITLE
Debugger hangs on very large arrays

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaDebug/Debugger.jl#236]
Due to the call to `repr` 
```julia
julia> @enter length(view(1:100_000_000,:)) # hangs for a long time
```
This was previously discussed in https://github.com/JuliaDebug/Debugger.jl/issues/65 but I now realised it is triggered by Base types as above.

**Comment by KristofferC** [comment]
The problem is that:

https://github.com/JuliaDebug/Debugger.jl/blob/4e33178985922af7dcdb6175916c4e2e26acf0ca/src/printing.jl#L12

takes a lot of time when a variable is very large. Not sure what the best solution is.

**Comment by dlfivefifty** [comment]
could you change it to call whatever the REPL does? That returns instantly:
```julia
julia> view(1:100_000_000,:)
100000000-element view(::UnitRange{Int64}, :) with eltype Int64:
         1
         2
         3
         4
         5
         6
         7
         8
         9
        10
        11
        12
        13
        14
        15
        16
        17
        18
        19
        20
        21
        22
        23
        24
        25
        26
        27
        28
         ⋮
  99999974
  99999975
  99999976
  99999977
  99999978
  99999979
  99999980
  99999981
  99999982
  99999983
  99999984
  99999985
  99999986
  99999987
  99999988
  99999989
  99999990
  99999991
  99999992
  99999993
  99999994
  99999995
  99999996
  99999997
  99999998
  99999999
 100000000
```

**Comment by KristofferC** [comment]
Putting 10 of those after eachother is not going to be very nice. 

I'm guessing we could make a custom `IO` that throws after a certain number of bytes have been written to it and then catch that exception and extract the data from it. Hacky, but might work.

**Comment by dlfivefifty** [comment]
What about something like
```Julia
_repr(a::AbstractArray) = length(a) > 100 ? “ suppressed” : repr(a)
_repr(a) = repr(a)
```
Should fix the known cases at least.

**Comment by KristofferC** [comment]
Yeah, but I guess that would fails for

```jl
struct Foo
    a::AbstractArray
end
```

,right?

**Comment by dlfivefifty** [comment]
Yes of course. Would be a good stopgap measure though

**Comment by KristofferC** [comment]
I think the custom IO is the way to go. Should be super easy to implement if someone wants to start hacking on Debugger.jl. Otherwise, I'll get to it pretty soon.
