### ISSUE TITLE
Debugger.jl halted on the line of JSON.parse() 

### ISSUE THREAD

**Issue by zhangliye** [JuliaDebug/Debugger.jl#243]
I tested Debugger using Julia1.3 and Julia 1.2. I use command `n` to debug line by line. When it encounter the line using JSON.jl package. Debugger.jl running a long time and halted there, and can not go to the next line. The demo code is as follows.

`
using JSON

function f()
f_path = raw"C:\test.json"
txt = read( f_path , String )
vessel_char = JSON.parse( txt ) ## stopped here, and vs code has no response

return c 

end

d = f()
`

**Comment by KristofferC** [comment]
The debugger is very slow How big is the JSON file? What happens if you try with a small file?

**Comment by zhangliye** [comment]
When I use the compiled mode of the debugger.jl, it can pass through.  The file is very small and I found a lot of people talked about the speed.  If I use interpreted mode,  the laptop keeps running and halted there.

**Comment by KristofferC** [comment]
>  I found a lot of people talked about the speed.

The speed of what? The debugger backend is very slow. Anyway, this seems to be expected. Ref https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/206
