### ISSUE TITLE
Document switching between repl modes

### ISSUE THREAD

**Issue by jlapeyre** [JuliaDebug/Debugger.jl#244]
I can't find this documented in the README. By examining the source code, you find that  "`" switches from the debug repl to the julia repl, and backspace switches back.

**Comment by KristofferC** [comment]
I thought it says:

> `` `stuff: run stuff in the current function's context``

Could be made more explicit perhaps.

**Comment by jlapeyre** [comment]
Yes. I saw that after I found it in the source. Now I see what it means. Not clear that it switches repl modes. I only knew to look for how after seeing it is possible in a recording of your presentation.

**Comment by KristofferC** [comment]
Would be good to get a more explicit comment, I agree.

**Comment by lassepe** [comment]
I think the README is pretty clear on this now:

> In addition to these debugging commands, you can type ` to enter "evaluation mode" indicated by a prompt $i|julia>. [...]

> Hit backspace as the first character of the line to return to "debug mode."

**Comment by KristofferC** [comment]
Yep.
