### ISSUE TITLE
Debugging inside map closures

### ISSUE THREAD

**Issue by baggepinnen** [JuliaDebug/Debugger.jl#250]
Consider the debugging of the following function
```julia
function debugfun(non_accessible_variable)
    garbage = ones(10)
    map(1:10) do i
        a = 5
        garbage[i] + non_accessible_variable[i]
    end
end

julia> @enter debugfun(randn(10))

# step into the closure

debug> a
5

debug> non_accessible_variable
ERROR: UndefVarError: non_accessible_variable not defined
Stacktrace:
 [1] top-level scope at none:0
```
There are a few problems associated with debugging what's happening inside the `map` closure.
- It's very hard to step into the closure. The only feasible way is to set a breakpoint there.
- When the debugger is inside the closure, it does not see some variables, such as `non_accessible_variable` above.

**Comment by KristofferC** [comment]
It would help if the example here could be minified a bit. But yeah, the lowering here is kinda tricky to "map back" to the source code.

**Comment by baggepinnen** [comment]
I minified the example in the OP so that it can be run

**Comment by KristofferC** [comment]
Just to explain the problem. When we are inside the closure, there is, in fact, no variable `non_accessible_variable`. In "reality", that variable is stored inside a struct (called `#self#`) and all accesses to it has been rewritten in the lowering process:

```
In #5(i) at REPL[4]:4
 1  1 ─      a = 5
●2  │        nothing
>3  │   %3 = (getfield)(#self#, :garbage)
 4  │   %4 = (getindex)(%3, i)
 5  │   %5 = (getfield)(#self#, :non_accessible_variable)
 6  │   %6 = (getindex)(%5, i)
 7  │   %7 = (+)(%4, %6)
 8  └──      return %7
```

We can access it by getting the corresponding field of `#self#`.

```
1|julia> var"#self#".non_accessible_variable
10-element Array{Float64,1}:
 -1.2780633828763326
 -0.8039029768210644
 -0.5342713409092642
```

It shouldn't be too hard to also make the fields in `#self#` available.

**Comment by KristofferC** [comment]
https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/388

**Comment by baggepinnen** [comment]
One more thing, "step to line" does not work if the cursor is on a line in the closure. I understand the reason, but if it did work it would be very convenient!
