### ISSUE TITLE
Declaring new variables in "evaluation mode"?

### ISSUE THREAD

**Issue by lassepe** [JuliaDebug/Debugger.jl#258]
Is it possible to declare new variables in evaluation mode (i.e. after hitting `` ` ``)?

Currently, if I declare a new variable I do not get an error but it remains undefined afterwards:
```julia
1|julia> x = 1
1|julia> x
ERROR: UndefVarError: x not defined
```

**Comment by KristofferC** [comment]
You can declare them with `global`. It isn't really possible to declare new local variables.
