### ISSUE TITLE
Clear watch list between debug sessions?

### ISSUE THREAD

**Issue by lassepe** [JuliaDebug/Debugger.jl#259]
Currently, the watch list is not cleared between different debug sessions. If I first `@enter` some call `f(x)` and put something on the watch list with  `w add expr` (e.g. `w add length(x)`), that same expression will stay on the watch list for all future debug sessions until explicitly removed.

That is, if later I `@enter` another call `g(a, b)` that expression will still be on the watch list and is most likely not even meaningful for that call.

Is this the intended behavior? I can see this being convenient in cases where one debugs the same function multiple times (thus avoiding having to set up the watch list every time).

**Comment by KristofferC** [comment]
In my experience you often debug the same function multiple times so it seemed convenient to me to keep the watch list. It is simple enough to clear.
