### ISSUE TITLE
narrative style user docs

### ISSUE THREAD

**Issue by clarkfitzg** [JuliaDebug/Debugger.jl#262]
I wrote a draft [introductory narrative](http://webpages.csus.edu/fitzgerald/julia-debugger-tutorial/) for the Debugger package.

Are people interested in adding a version of this narrative to the official documentation? I'd edit out my personal comments, and incorporate other feedback. If not, well, that's fine- 3rd party blog posts also contribute to the ecosystem.

EDIT: updated URL

**Comment by clarkfitzg** [comment]
BTW, if there's a better venue to have this discussion, please point me there and I'll close this.

**Comment by timholy** [comment]
I haven't read this carefully, but I wouldn't take lack of action as a sign we didn't like it. Mostly that those of us who maintain this package are a bit overstretched. Are you still interested in getting this merged? If so we can reopen until the time that someone has time to review it.
