### ISSUE TITLE
Debugger does not break on @bp when using threads

### ISSUE THREAD

**Issue by herzfeldd** [JuliaDebug/Debugger.jl#273]
First of all, thanks for this great tool!

Unfortunately, break points don't appear to function correctly when using `Threads.@threads`. In particular, break points are never hit, even when explicitly placed in the code. `bp on error` seems to appropriately break if there is an error, but the stack trace just shows a call to `ccall(:jl_threading_run, Cvoid, (Any,), threadsfor_fun)`, not the stack for the actual thread. I am happy to break this into two separate issues if they should be tracked separately.

Here is a MWE:
```julia
module ModuleFoo
    import Debugger
    function foo()
        println("Running with $(Threads.nthreads()) threads.")
        Threads.@threads for i = 1:Threads.nthreads()
            foo_with_bp()
        end
    end

    function foo_with_bp()
        Debugger.@bp
        error("I should never get here")
    end
end

using Debugger
@run ModuleFoo.foo()
```

Note: This fails to break on `@bp` even when you aren't explicitly using more than on thread (i.e., does not break on `@bp` even when `JULIA_NUM_THREADS=1`).

Version Info:
  julia version 1.4.2
  [31a5f54b] Debugger v0.6.6

**Comment by KristofferC** [comment]
I think this is expected for now. The threading system goes into the Julia runtime where the interpreter loses track of it.

**Comment by davidanthoff** [comment]
See also https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/413.

**Comment by KristofferC** [comment]
Closing in favor of the upstream issue.
