### ISSUE TITLE
Add breakpoint support

### ISSUE THREAD

**Issue by KristofferC** [JuliaDebug/Debugger.jl#28]
Debugger.jl does some optimizations to not run things interpreted when that is not useful. However, breakpoints makes that a bit problematic since we need to run everything in interpreted mode.

I guess the simplest way forward would just be to swap out the optimization when there are any breakpoints present.

@timholy do you have any input here?

**Comment by timholy** [comment]
That's correct. Note that we'll also be unable to breakpoint in anything blacklisted (currently `Core.Compiler`, `Base.Threads`, and anything defined in `set_compiled_methods`).

**Comment by KristofferC** [comment]
Need docs and tests but implemented.
