### ISSUE TITLE
Regression displaying help

### ISSUE THREAD

**Issue by nandoconde** [JuliaDebug/Debugger.jl#287]
Hello.

I've noticed that Debugger help no longer prints correctly `\\` linebreaks in debugging REPL help command `?`.

I think this started happening after the regression #284 and its fix.

![Captura de pantalla 2021-03-22 125905](https://user-images.githubusercontent.com/9221284/111986590-742f6c00-8b0e-11eb-80f2-ea0b16a9457c.png)

Thanks for everything!

**Comment by KristofferC** [comment]
I'm pretty sure it is a regression in Julias Markdown rendering. Not much that can be done about it from here :/
