### ISSUE TITLE
Feature request: step straight into function when there are evaluations in the arguments

### ISSUE THREAD

**Issue by johnomotani** [JuliaDebug/Debugger.jl#309]
When using Debugger.jl from the REPL, I often find I have a function call like
```
@views foo!(a[:,j,i], b[j], c.bar)
```
and want to step into `foo!()`. Often, stepping into the evaluations of `getindex()`, `getproperty()`, etc. just get in the way.

After asking about this on Discourse (https://discourse.julialang.org/t/debugger-usage-step-over-evaluations-in-function-arguments-straight-into-the-function/77018) it seems the best current solution for this case is to use `se` to step over the evaluations in the arguments, and then finally `s` to step into the function. When there are a lot of arguments, it becomes quite easy to miss the point where I've finally reached the `foo!()` call that I want to step in to.

I think it would be nice to have a single command (like `sf` maybe, for step-into-function?) that would cover this case in a single command.

**Comment by KristofferC** [comment]
So step into the last function on the given line?

**Comment by johnomotani** [comment]
> So step into the last function on the given line?

Yes, I guess that would be it :+1:

**Comment by KristofferC** [comment]
This has been fixed in the latest version (might have to wait a bit). The command to use is `sl`.
