### ISSUE TITLE
debug hangs when debug code with Mnist dataset

### ISSUE THREAD

**Issue by wztdream** [JuliaDebug/Debugger.jl#319]
Hi,
I am using vscode and trying to debug [this repo](https://github.com/FishAres/RNP/blob/master/scripts/vae_mnist.jl), I set break point at line 32

https://github.com/FishAres/RNP/blob/c9571301627cb4989a7cada18de168bc257fc03d/scripts/vae_mnist.jl#L32

then press F5 for debug, but my computer keep running and not stop at least for 20mim. I tested the debug function for simple code, they works well. So I suspect the debugger function seems can not deal with Mnist dataset.

I think vscode are using this repo as backend, so report it here. I also follow documentation and use Debugger in REPL and the issue is same.

**Comment by KristofferC** [comment]
It might be that the code is too computationally heavy for the debugger. The debugger is currently quite slow so try with a smaller workload.
