### ISSUE TITLE
Integration with code editors.

### ISSUE THREAD

**Issue by branc116** [JuliaDebug/Debugger.jl#5]
This looks awesome, was quite happy to see this working as good as it did, considering that the project is quite new.

Are you thinking about integration with code editors (e.g. VS code)  or do you know someone who is?

It'd be quite nice to see you joining forces with [Julia Editor support](https://github.com/JuliaEditorSupport) !

**Comment by KristofferC** [comment]
While the name is new and shiny, it should be noted that the project the code comes from is quite old (see ASTInterpreter2.jl).

I know @pfitszeb has Atom IDE (Juno) working well with at least the previous version. Regarding vscode, I don't think there is any progress there yet.

**Comment by zxj5470** [comment]
This repository is still working.
Waiting for
https://github.com/JuliaDebug/Debugger.jl/blob/master/src/Debugger.jl#14
```
# TODO: Work on better API in JuliaInterpreter and rewrite Debugger.jl to use it
```
a better API~

I haven writen some wacky codes to implement the debugger: 
https://github.com/ice1000/julia-intellij/blob/master/res/org/ice1000/julia/lang/execution/IntelliJDebugger.jl#140

**Comment by davidanthoff** [comment]
@KristofferC is correct: we are watching all of this here with great interest from the VS Code side of things, but currently no one is working on any integration. Hopefully someone will eventually!

**Comment by zxj5470** [comment]
> @KristofferC is correct: we are watching all of this here with great interest from the VS Code side of things, but currently no one is working on any integration. Hopefully someone will eventually!

No one? I don't think so 😂 julia-intellij has finished most of functional for the debugger based on ASTInterpreter2 and DebuggerFramework

**Comment by timholy** [comment]
Most of the current development effort is going to JuliaInterpreter; be a bit patient, I think we will have something quite interesting fairly soon.

**Comment by timholy** [comment]
(If you want to track status, the big push currently is https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/13.)

**Comment by dehann** [comment]
The Debugger is awesome, thanks happy to see this coming online again!  I would add a +1 for clean integration with Editors please.  Should be better than PyCharm ;-)

**Comment by KristofferC** [comment]
Almost all functionality for this is now in https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/126 so people interesting in writing other frontends for a debugger should most likely do it on top of that.

**Comment by timholy** [comment]
Specifically, see JuliaInterpreter's `debug_command` (which is exported and has a docstring): that should be the common ground for all debugger implementations. IIUC this package is morphing basically into a REPL mode; Rebugger will be another REPL mode; Juno will likely be the first graphical IDE; all three should target the `debug_command` API of JuliaInterpreter. (Currently Rebugger does not, but give me a couple days...)
