### ISSUE TITLE
Ideas for an in debug mode interface to adding breakpoints

### ISSUE THREAD

**Issue by KristofferC** [JuliaDebug/Debugger.jl#59]
Currently, the documented way to add breakpoints is using the JuliaInterpreter API. This is fine with the exception that one might want to add breakpoints during execution of the program, when one is in the debug mode. There is however nothing wrong with the JuliaInterpreter API, in fact, the fact that it is normal julia syntax is a strength. So we need to just be able to access it from the debug mode.

If we think about it, we already have a way to evaluate julia code in the debug mode and that is using the `'` command to go into evaluation mode in the current frame context. Perhaps we could piggyback on that and just make sure that JuliaInterpreter is always available on that mode. We could easily do that by interpreting something like `JuliaInterpreter = $(JuliaInterpreter)` into the expression getting evaluated. We would probably lose tab completion though.

Implementing and documenting a complete new API for manipulating breakpoints seems like a big waste of time so I think something like this is a good way forward.

**Comment by timholy** [comment]
Another option would be to set up special key bindngs to do that. Obviously some of the good choices (e.g., Meta-b) are already taken.

**Comment by KristofferC** [comment]
Or we can just make `@breakpoint` and `breakpoint` available in the julia mode of the debug interface and you just use it from there. I guess one of the confusing things might be that you are evaluating things in the module of the frame while you might expect to use the same namespace as if you where in the normal Julia REPL.

**Comment by timholy** [comment]
Yeah, that seems more consistent with the philosophy of Debugger.jl. Keybinding magic is a bit painful, no choice seems to work for everyone, and people who like the keybinding magic can use Rebugger. This choice would educate users into the "real" interface (which is always a way to help convert users into developers, muahahaha...

**Comment by KristofferC** [comment]
Implemented
