### ISSUE TITLE
Breakpoint symbol looks bad in some terminals

### ISSUE THREAD

**Issue by KristofferC** [JuliaDebug/Debugger.jl#98]
![image](https://user-images.githubusercontent.com/1282691/54536316-cb832a80-4990-11e9-9fda-1f2e432a1610.png)

Also, it just shows a square in cmd.exe. This is why we can't have pretty things.

**Comment by pfitzseb** [comment]
Maybe use those instead:
![grafik](https://user-images.githubusercontent.com/6735977/54537038-1a7d8f80-4992-11e9-83a0-962db67b27eb.png)

**Comment by KristofferC** [comment]
That's the one I am using...

**Comment by pfitzseb** [comment]
But those look fine for me in cmd.exe (with Consolas, Courier New, and Source Code Pro)...

**Comment by KristofferC** [comment]
Ok, swapping the font was enough to fix it. `◐` still squares though

**Comment by KristofferC** [comment]
I guess squares will be the conditional breakpoints for cmd users :D

**Comment by pfitzseb** [comment]
How about `●`, `c`, and `○`? `c` for **c**ondtional breakpoint and it also looks lke half a circle? :D

**Comment by KristofferC** [comment]
Meh.
